{{- if .Values.ingress.enabled }}

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "react-serve.fullname" . }}-ingress
  labels:
    app: {{ template "react-serve.name" . }}
    environment: {{ .Values.environment }}
    release: {{ .Release.Name }}
spec:
  ingressClassName: {{ required "ingress.ingressClassName" .Values.ingress.ingressClassName | quote }}
  rules:
    - host: {{ required "ingress.hostname" .Values.ingress.hostname | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ template "react-serve.fullname" . }}-svc
                port:
                  number: 80

  {{- if .Values.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.ingress.host | quote }}
      secretName: {{ required "ingress.tls.secretName" .Values.ingress.tls.secretName }}
  {{- end }}

{{- end }}
